### ISSUE TITLE
Clone from github owner all repos - it restricted to 100 repos

### ISSUE THREAD

**Issue by ivan-sre** [rafi/gits#2]
Hello Rafi!

I'm trying to clone all repos from specific owner in github, it stopped after 100 repos are cloned.
How to override this value?

Regards,
Ivan (Tikal)

**Comment by rafi** [comment]
Hey Ivan, you can change it here https://github.com/rafi/gits/blob/e9c65e65ef3ccbe6784db17bee7ab0322b913e56/pkg/providers/github.go#L72
Add a `0` there :] It's in my TODO list to add pagination or raise the limit there...

**Comment by ivan-sre** [comment]
Thank you!

**Comment by rafi** [comment]
I've implemented pagination ~in the `next` branch~, you can try it out:
```sh
brew upgrade rafi/tap/gits
```
